// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnkgfmnxfuygrgjgcuyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdua2dmbW54ZnV5Z3JnamdjdXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDYxOTAsImV4cCI6MjA1OTMyMjE5MH0.pQez3SQN8Whqk0nbehPqTSNfFddPZlYMJP-6n8VWhfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);